### ISSUE TITLE
Inventory Tabs compatibility

### ISSUE THREAD

**Issue by SimonMeskens** [moonfather1/workshop_for_handsome_adventurer#1]
https://www.curseforge.com/minecraft/mc-mods/inventory-tabs-forge

Would be very nice to have compatibility with this mod. Crafting tables work perfectly and show the icon + name of the block, but workstations, on account of how they're programmed, show a blank icon and no name. The name thing seems easy enough, just an extra few lines in the lang. I think the icon might use the item icon, which the in-world workstation might not have?

**Comment by moonfather1** [comment]
hmm... there was a bug recently with obtaining clone item (item you get when you middle click a block). maybe you have that version. or i didn't upload a fix?

i'll check latest versions now...

EDIT:
indeed i forgot to upload the fix on 1.18.2 although i pushed the code a while ago. that's taken care of now.

unfortunately, it doesn't fix inventory tabs display as i hoped.

**Comment by moonfather1** [comment]
i tried out this IT mod (first time i heard of it and i while i'm not adding it to mods i play with, i understand that people would play with it (which is more than i can say for 99% of the mods). 

while neat in general, the execution is lacking. first flaw is that it shows tabs for block entities that don't have menus (in-game windows). it shouldn't be a problem. they just need to call getMenuProvider and see if the block has a menu. 

second flaw is that they right-click blocks instead of opening guis manually (a client mod can't do that). i have added a bunch of my block to their blacklist because those right-clicks may be unwanted. when you click a tab that is my bookshelf, a book from a certain slot gets pulled into hotbar (if slot is full). that's not a nice implementation; it might activate machines, etc. but if they fix the first problem, this second problem would just go away.

and then there is compatibility with my tables...

while i could provide a blockitem and thus resolve the issue of empty tab (image and text), i will not. it is easier for their author to fallback to "clone item" (middle-click item) if blockitem doesn't exist. plus it would mean supporting other such blocks.

finally, i really don't like how it looks when my tables move the gui to the right and inventory tabs stay in the middle. and you can confirm that it can be detected because jei moves the item list away when my gui moves to the right. would be nice if they had a list of blocks that have tabs right aligned.

perhaps you can direct IT's original dev and forge port dev here or (even better) open issues at their repositories? i would be willing to assist (to a reasonable degree) in improving things on their end.

**Comment by moonfather1** [comment]
to clarify (because people misunderstand me all the time), i'm not saying _i don't care, have their dev fix it_... i do care. but there is proper way of doing this and it isn't on my end.

> The name thing seems easy enough, just an extra few lines in the lang

it's easy. i would have done it even if it weren't easy.

but i spent three full days implementing EveryCompat support (automatically makes tables, bookshelves, etc. in literally every wood type mods provide). so i am uninterested in solutions that won't cover those dynamically added tables. and adding a few lines to a language file won't cover them.

do you know how i make the one probe or jade show proper text and image for my workstation? i did nothing. they take the "middle-click" item and they display it on hover. so if Inventory Tabs does that (even as a fallback although it would have been my first choice) it would support my workstations, and also my workstations from addon mods and any other multiblock structures that seem supported by the one probe.

so do we agree that that (above) would be a proper way to go about this?

**Comment by SimonMeskens** [comment]
Don't worry, all of this makes sense and I can relate to being misunderstood :)

Thanks for the lengthy response, I do indeed agree that's the way to go. I'll open some issues.
