### ISSUE TITLE
[REGQUEST] Add vanilla "nether-wood" types.

### ISSUE THREAD

**Issue by PadderFance** [moonfather1/workshop_for_handsome_adventurer#4]
Just a small request. Hopefully not much work with.
Minecraft Vanilla has two "woods", this mod is not creeating blocks for: crimson and warped (nether wood).
Hopefully you can add this.

**Comment by moonfather1** [comment]
actually, work is minimal. in the old days, i'd have to add models, blockstates, loot tables, tag entries... now, with a magical wood support system, it just one short row.

however this request comes at a bad time - i've lately been told that i add too much "bloat". so now i have to weight: are there more weirdos (no offense meant) who like those ugly nether wood or more weirdos who think i added bloat?

i don't know.
now i'm thinking i'll add them behind a config. you may need to add a line to the config (because you already have it) or delete it so that it regenerates with a new line... i'll tell you what to do when i'm done.

i'm working on a new version (support for c4's polymorph). all do this when that's done.

**Comment by PadderFance** [comment]
If you want to have my opinion:

A "wood-mod" which adds additional uses for different wood types should support EVERY wood in vanilla and may have support for additional wood types from other mods. (But thanks to the mod "every compat", this additional support isn't required anymore.)

Calling about "weird" things or "weirdos". For me it is weird not having all wood-types. Adding "bloat" does not mean, to support wood types someone do not like, it could mean, to add items/blocks which may not neccessary. My honest opinion: IDK. For me your mod does not contain bloat.

My suggestion: Add your Blocks/Items to the config and not the wood types. If someone thinks one specific item/block is bloat, he/she can disable it.

**Comment by moonfather1** [comment]
idea of adding types of blocks to a config is smart and best way to fight any bloat, but there are complications - in order to minimize the chance of recipe conflicts, i made it so that only one bookshelf type is craftable from slabs and nuggets, and the rest are craftable from it, in chain. similarly for toolracks. so allowing a user to disable "open double bookshelf" makes a hole in that recipe chain.

every compat shouldn't still support the workshop. i agreed with them to cut support when i made my internal support. maybe i should check that.

**Comment by moonfather1** [comment]
and it's not that i don't think that i should support every wood type just because i find crimson palette ugly. i do.

but before i knew i would support modded wood somehow magically, i intended to have separate addons. first one i made was a sample addon, including warped and crimson, intentionally omitted to demonstrate how to make an addon. and i also made a byg addon, with a hope that people would make a few more, looking at those two sample addons.

then those two addon mods became obsolete and i never got around to adding warped and crimson into the main mod even though it's a one-line job now.
